import Link from 'next/link'
import './globals.css'
import { Open_Sans } from 'next/font/google'
import { Nanum_Gothic } from 'next/font/google'


const inter = Open_Sans({ subsets: ['latin'] })
const Nanum = Nanum_Gothic({ 
  weight: '700',
  subsets: ['latin']
 })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon : '/favicon.ico',
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={Nanum.className}>
        <header className='flex justify-between align-items:center p-8 border-b-orange-400'>
            <h1><Link href="/">Home</Link></h1>
            <nav className='flex justify-between items-center gap-10'>
                <Link href="/products">Products</Link>
                <Link href="/contact">Contact</Link>
                <Link href="/about">About</Link>
                
            </nav>
        </header>
        {children}
        <footer className={Nanum.className}>
          <strong className='text-3xl'>Footer</strong></footer>
      </body>
    </html>
  )
}
